import { useRouter } from 'next/router'
import Head from "next/head"
import styles from "@/styles/Home.module.css"
import Header from "../../components/Header"
import SideBar from '../../components/Sidebar'
import Link from "next/link"
import { Button } from "react-bootstrap"
import axios from "axios"
import { useEffect,useState,useRef} from 'react'
import ReactToPrint from 'react-to-print';
import { AiFillPrinter} from "react-icons/ai";
import { IconContext } from "react-icons";

//const componentRef=useRef()

async function GetUserDetails(id){
  const res = await axios({
    url:"http://localhost:3000/duty_log/"+id,
    withCredentials:true,
    method:"GET"
  });
  return res.data;
}

function printDiv(divName) {

if (typeof document !== 'undefined') {
  if(document.getElementById(divName) != null){
    var printContents=document.getElementById(divName).innerHTML;
}

  var originalContents = document.body.innerHTML;

  document.body.innerHTML = printContents;

  window.print();

  document.body.innerHTML = originalContents;
}}
const Post = () => {
  
  const [duty,setDuty] = useState({});
  const router = useRouter();
  const { id } = router.query
  useEffect(()=>{
    if(!router.isReady) return;
    const {id} = router.query
    GetUserDetails(id).then((data)=>{
      setDuty(data);
      //console.data
      console.log(data);
      
    });
  }, [router.isReady]);
  const componentRef = useRef();
  return( 
    <>
        <Head>
        
          <title>User Details</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          
        </Head>
        <Header/>
        <SideBar/> 
        <main className={styles.main}>
       
          <div style={{ marginTop: "1rem ",  height: '80%'}}>  
          <div style={{fontSize:"1rem",marginTop: "1rem",right:10,position:'absolute'}}>
          <IconContext.Provider value={{ color: "blue", className: "global-class-name"  }}>
          <ReactToPrint
        trigger={() => <button><AiFillPrinter/></button>}
        content={() => componentRef.current}
      />
      </IconContext.Provider>
          </div>
          <div id="printableArea" ref={componentRef} className="p-5">
         
            <div style={{fontSize:"4rem",marginTop: "1rem",marginBottom:"2rem",marginLeft: 10,marginRight: 10,}}>
              <span>DUTY DETAILS</span>
              <hr  style={{
                color: '#000000',
                backgroundColor: '#000000',
                height: 2.5,                
                }}/>
            </div>
          
                               
            <table class="table">
            {
                  
              <tbody>
                <tr>
                    <th scope="row">1.</th>
                    <td>Vehicle no:</td>
                    
                    <td>{duty.vehicle_id && (<>{duty.vehicle_id. vehicle_crp_no}{"   "} - {"   "}{duty.vehicle_id.registration_no}</>)}</td>
                  
                </tr>
                <tr>
                    <th scope="row">2.</th>
                    <td>Date:</td>
                    <td>{(duty.date)}</td>
                </tr>
                <tr>
                    <th scope="row">3.</th>
                    <td>From:</td>
                    <td>{duty.from}</td>
                </tr>
                <tr>
                    <th scope="row">4.</th>
                    <td>To:</td>
                    <td>{duty.to}</td>
                </tr>
                <tr>
                    <th scope="row">5.</th>
                    <td>Out Time:</td>
                    <td>{duty.out_time}</td>
                </tr>
                <tr>
                    <th scope="row">6.</th>
                    <td>In Time:</td>
                    <td>{duty.in_time}</td>
                </tr>
                <tr>
                    <th scope="row">7.</th>
                    <td>Meter Count:</td>
                    <td>{duty.meter_count}</td>
                </tr>
                <tr>
                    <th scope="row">8.</th>
                    <td>Km Run:</td>
                    <td>{duty.km_run}</td>
                </tr>
                <tr>
                    <th scope="row">9.</th>
                    <td>Purpose:</td>
                    <td>{duty.purpose}</td>
                </tr>
                <tr>
                    <th scope="row">10.</th>
                    <td>Indent No:</td>
                    <td>{duty.indent_no}</td>
                </tr>
                <tr>
                    <th scope="row">11.</th>
                    <td>Approved By Mto:</td>
                   
                    <td>{(duty.approved_by_mto==true)?"Yes":"NO"}</td>
                </tr>
                                                    
              </tbody>
                }
            </table>
          
          </div>  
          </div>  
        </main> 
    </>
  )  
}
export default Post