import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Script from "next/script";
import Header from "../../components/Header";
import SideBar from "../../components/Sidebar";
import Scripts from "../../components/Scripts";
import { useEffect, useState } from "react";
import axios from "axios";
import Router from "next/router";
import Link from "next/link";
import { Button, Row } from "react-bootstrap";
import dateFormat from "dateformat";

async function GetDuties() {
  const res = await axios({
    url: "http://localhost:3000/duty_log/",
    method: "GET",
    withCredentials: true,
  });
  return res.data;
}

function call() {
  <th scope="row">
    <i
      className="bi bi-truck"
      style={{
        color: "red",
        fontSize: "1rem",
      }}
    ></i>
  </th>;
}

export default function Home() {
  const [duties, setDuties] = useState([]);
  useEffect(() => {
    GetDuties().then((data) => {
      setDuties(data);
    });
  }, []);
  function OpenLink(link) {
    Router.push("/admin/duties/" + link);
  }
  return (
    <>
      <Head>
        <title>List Duties</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <Header />
        <SideBar />

        <main id="main" className=" col-lg-11 main mt-0">
          <h1>All Duties</h1>
          <Row>
            <div className="col-lg-8">
              <div className="card opac-90">
                <div className="card-body">
                  <table className="table table-hover">
                    <thead>
                      <tr>
                        <th scope="col">DATE</th>

                        <th scope="col">Vehicle No</th>
                        <th scope="col">OUT TIME</th>
                        <th scope="col">Mission Satus</th>
                      </tr>
                    </thead>
                    <tbody style={{ cursor: "pointer" }}>
                      {duties.map((duty, index) => {
                        var vv = new Date(duty.date);
                        var mission = duty.mission_ended;
                        let color = "#D0F5BE";
                        let textColor = "#0C134F";
                        var v1;
                        if (mission) {
                          v1 = "Completed";
                          color = "#FBFFDC";
                          textColor = "green";
                        } else {
                          v1 = "Active";
                        }
                        return (
                          <tr
                            key={index + 1}
                            onClick={() => OpenLink(duty._id)}
                            style={{ backgroundColor: color }}
                          >
                            <th scope="row">
                              {duty.out_datetime &&
                                dateFormat(duty.out_datetime, "dS mmmm, yyyy")}
                            </th>
                            <td>{duty.vehicle&&duty.vehicle.registration_no}</td>
                            <td>
                              {duty.out_datetime &&
                                dateFormat(duty.out_datetime, " h:MM TT")}
                            </td>

                            <td style={{ color: textColor }}>
                              {v1 === "Active" && (
                                <>
                                  <span className="blinking">Active</span>
                                </>
                              )}
                              {v1 === "Completed" && (
                                <>
                                  <span>Completed</span>
                                </>
                              )}
                            </td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
            <div
              className="col-lg-3 card p-4 m-1 opac-80"
              style={{ maxHeight: "20vh" }}
            >
              <Link href={"/admin/duties/add"}>
                <Button className="w-100 mb-1 btn-warning">Add Duties</Button>
              </Link>
              <Link href={"/admin/duties/update"}>
                <Button className="w-100 mb-1 btn-dark">Update Duties</Button>
              </Link>
            </div>
          </Row>
        </main>
      </main>
      <Scripts />
      <Script src="/assets/js/main.js"></Script>
    </>
  );
}
