import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Script from "next/script";
import Header from "../../components/Header";
import SideBar from "../../components/Sidebar";
import Scripts from "../../components/Scripts";
import { useEffect, useState } from "react";
import axios from "axios";
import Link from "next/link";
import Router from "next/router";
import { Button, Row } from "react-bootstrap";

async function GetDrivers() {
  const res = await axios({
    url: "http://localhost:3000/drivers/",
    method: "GET",
    withCredentials: true,
  });
  return res.data;
}

export default function Home() {
  const [drivers, setDrivers] = useState([]);
  const [updateOption, setupdateOption] = useState(false);
  const [deleteOption, setdeleteOption] = useState(false);

  useEffect(() => {
    GetDrivers().then((data) => {
      data.sort((a, b) => a.vehicle_sl_no - b.vehicle_sl_no);
      setDrivers(data);
    });
  }, []);

  function OpenLink(link) {
    Router.push("/admin/drivers/" + link);
  }
  return (
    <>
      <Head>
        <title>List Vehicles</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <Header />
        <SideBar />

        <main id="main" className="col-lg-11 main mt-0 opac-80">
          <Row className="p-1"></Row>
          <div className="col-lg-12 d-flex">
            <div className="col-lg-8 m-1">
              <div>
                <h1>Available Drivers</h1>
                <div className="card p-3">
                  <table className="table table-hover">
                    <thead>
                      <tr>
                        <th scope="col">Sl No</th>
                        <th scope="col">Name</th>
                        <th scope="col">License No</th>
                        <th scope="col">Rank</th>
                        <th scope="col">Available</th>
                      </tr>
                    </thead>
                    <tbody style={{ cursor: "pointer" }}>
                      {drivers.map((driver, index) => {
                        if (driver.available) {
                          return (
                            <tr
                              key={index + 1}
                              onClick={() => OpenLink(driver._id)}
                            >
                              <td>{index + 1}</td>
                              <td>{driver.name}</td>
                              <td>{driver.license_no}</td>
                              <td>{driver.rank}</td>
                              <td style={{ color: "green" }}>Available</td>
                            </tr>
                          );
                        }
                      })}
                    </tbody>
                  </table>
                </div>
              </div>
              <div>
                <h1>Drivers On Duty</h1>
                <div className="card p-3">
                  <table className="table table-hover">
                    <thead>
                      <tr>
                        <th scope="col">Sl No</th>
                        <th scope="col">Name</th>
                        <th scope="col">License No</th>
                        <th scope="col">Rank</th>
                        <th scope="col">Available</th>
                      </tr>
                    </thead>
                    <tbody style={{ cursor: "pointer" }}>
                      {drivers.map((driver, index) => {
                        if (driver.available===false) {
                          return (
                            <tr
                              key={index + 1}
                              onClick={() => OpenLink(driver._id)}
                            >
                              <td>{index + 1}</td>
                              <td>{driver.name}</td>
                              <td>{driver.license_no}</td>
                              <td>{driver.rank}</td>
                              <td style={{ color: "red" }}>On Duty</td>
                            </tr>
                          );
                        }
                      })}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
            <div className="col-lg-3 card p-5 m-1">
              <Link href={"/admin/drivers/add"}>
                <Button className="w-100 mb-1">Add Driver</Button>
              </Link>
              <Link href={"/admin/drivers/"}>
                <Button className="w-100 mb-1">All Drivers</Button>
              </Link>
            </div>
          </div>
        </main>
      </main>
      <Scripts />
      <Script src="/assets/js/main.js"></Script>
    </>
  );
}
