import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Script from 'next/script'
import Header from '../../components/Header'
import SideBar from '../../components/Sidebar'
import Scripts from '../../components/Scripts'
import {useEffect, useState} from 'react'
import Link from "next/link";
import axios from 'axios'
import Router from 'next/router'
import { Button } from "react-bootstrap";
import { Row } from 'react-bootstrap'

async function GetDrivers() {
    const res = await axios({url: "http://localhost:3000/drivers/", method: "GET", withCredentials: true});
    return res.data;
}


export default function Home() {
    const [drivers, setDrivers] = useState([]);
    useEffect(() => {
        GetDrivers().then((data) => {
            setDrivers(data);
        });
    }, []);
    function OpenLink(link) {
        console.log(link);
        Router.push('/admin/drivers/' + link);
    }
    return (
        <>
            <Head>
                <title>List Drivers</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>

            </Head>
            <main className={
                styles.main
            }>
                <Header/>
                <SideBar/>
                <main id="main" className=" col-lg-11 main mt-0">
          <h1>All Drivers</h1>
          <Row>
            <div className="col-lg-8">
              <div className="card opac-90">
                <div className="card-body">
                  <table className="table table-hover">
                    <thead>
                      <tr>
                                <th scope="col">Sl No</th>
                                <th scope="col">Driver Name</th>
                                <th scope="col">License No</th>
                                <th scope="col">Rank</th>
                                <th scope="col">Start Date</th>
                                <th scope="col">End Date</th>
                              
                            </tr>
                        </thead>
                        <tbody style={
                            {cursor: "pointer"}
                        }>
                            {
                            drivers.map((driver, index) => {
                                return (
                                    <tr key={
                                            index + 1
                                        }
                                        onClick={
                                            () => OpenLink(driver._id)
                                    }>
                                        <td>{
                                            index+1
                                        }</td>
                                        <td>{
                                            driver.name
                                        }</td>
                                        <td>{
                                            driver.license_no
                                        }</td>
                                        <td>{
                                            driver.rank
                                        }</td>
                                        <td>{
                                        driver.date_from
                                        }</td>
                                        <td>{
                                        driver.date_to
                                        }</td>
                                        
                                    </tr>
                                )
                            })
                        } </tbody>
                    </table>
                
                    </div>
            </div>
                    </div>
            <div
              className="col-lg-3 card p-4 m-1 opac-80"
              style={{ maxHeight: "20vh" }}
            >
              <Link href={"/admin/drivers/add"}>
                <Button className="w-100 mb-1 btn-warning">Add Drivers</Button>
              </Link>
             
            </div>
          </Row>
        </main>

            </main>
            <Scripts/>
            <Script src="/assets/js/main.js"></Script>
        </>
    )
}
