import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Script from 'next/script'
import Header from '../../components/Header'
import SideBar from '../../components/Sidebar'
import Scripts from '../../components/Scripts'
import {useEffect, useState} from 'react'
import axios from 'axios'
import Router from 'next/router'

async function GetDrivers() {
    const res = await axios({url: "https://projectx-production.up.railway.app/drivers/", method: "GET", withCredentials: true});
    return res.data;
}


export default function Home() {
    const [drivers, setDrivers] = useState([]);
    useEffect(() => {
        GetDrivers().then((data) => {
            setDrivers(data);
        });
    }, []);
    function OpenLink(link) {
        console.log(link);
        Router.push('/admin/drivers/' + link);
    }
    return (
        <>
            <Head>
                <title>List Drivers</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>

            </Head>
            <main className={
                styles.main
            }>
                <Header/>
                <SideBar/>

                <main id="main" className=" col-lg-9 main">
                    <h1>
                        All Drivers
                    </h1>
                                <hr  style={{
                                    color: '#000000',
                                    backgroundColor: '#000000',
                                    height: 2.5,
                                    borderColor : '#000000'
                                    }}/>
                    <table className="table table-hover">
                        <thead>
                            <tr>
                                <th scope="col">Sl No</th>
                                <th scope="col">Driver Name</th>
                                <th scope="col">License No</th>
                                <th scope="col">Rank</th>
                                <th scope="col">Start Date</th>
                                <th scope="col">End Date</th>
                                <th scope="col">Approved by MTO</th>
                            </tr>
                        </thead>
                        <tbody style={
                            {cursor: "pointer"}
                        }>
                            {
                            drivers.map((driver, index) => {
                                return (
                                    <tr key={
                                            index + 1
                                        }
                                        onClick={
                                            () => OpenLink(driver._id)
                                    }>
                                        <td>{
                                            driver.sl_no
                                        }</td>
                                        <td>{
                                            driver.name
                                        }</td>
                                        <td>{
                                            driver.license_no
                                        }</td>
                                        <td>{
                                            driver.rank
                                        }</td>
                                        <td>{
                                        driver.date_from
                                        }</td>
                                        <td>{
                                        driver.date_to
                                        }</td>
                                        <td>{
                                        driver.approval_mto
                                        }</td>
                                    </tr>
                                )
                            })
                        } </tbody>
                    </table>
                </main>

            </main>
            <Scripts/>
            <Script src="/assets/js/main.js"></Script>
        </>
    )
}
