import { useRouter } from "next/router";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "../../components/Header";
import SideBar from "../../components/Sidebar";
import axios from "axios";
import { useEffect, useState, useRef } from "react";
import { Row, Button } from "react-bootstrap";

async function GetMemoDetails(id) {
  const res = await axios({
    url: "http://localhost:3000/defectmemos/" + id,
    withCredentials: true,
    method: "GET",
  });
  return res.data;
}

const Post = () => {
  const [memo, setMemos] = useState({});
  const router = useRouter();
  const { id } = router.query;
  useEffect(() => {
    if (!router.isReady) return;
    const { id } = router.query;
    GetMemoDetails(id).then((data) => {
      setMemos(data);
    });
  }, [router.isReady]);
  const componentRef = useRef();
  return (
    <>
      <Head>
        <title>Memo Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.icon" />
      </Head>
      <Header />
      <SideBar />
      <main className={styles.main}>
        <main id="main" className="main col-10 mt-0 opac-90">
          Hello Bhai
        </main>
      </main>
    </>
  );
};
export default Post;
