import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Script from "next/script";
import Header from "../../components/Header";
import SideBar from "../../components/Sidebar";
import Scripts from "../../components/Scripts";
import { useEffect, useState } from "react";
import axios from "axios";
import Router from "next/router";

import { Button, Row } from 'react-bootstrap';
import Link from "next/link";
import dateFormat from "dateformat";



async function GetCards() {
  const res = await axios({
    url: "http://localhost:3000/job_card/",
    method: "GET",
    withCredentials: true,
  });
  return res.data;
}

async function createJobCard(event) {
  event.preventDefault();
  var data = {
    vehicle_no: event.target.vehicle_no.value,
    date:event.target.date.value,
    mechanic_name:event.target.mechanic_name.value,
    particular_work:event.target.particular_work.value,
    parts_used:event.target.parts_used.value,
    sign_of_mt_incharge:event.target.sign_of_mt_incharge.value,
    remarks:event.target.remarks.value,
    issue_voucher_number:event.target.issue_voucher_number.value,
    work_order_no:event.target.work_order_no.value,
    crp_no:event.target.crp_no.value
  };

  const res = await axios({
    url: "http://localhost:3000/job_card/add",
    withCredentials: true,
    method: "POST",


    data: data,
  });
}

export default function Home() {
  const [cards, setCards] = useState([]);
  useEffect(() => {
    GetCards().then((data) => {
      setCards(data);
    });
  }, []);
  function OpenLink(link) {
    Router.push('/admin/workshop/' + link);
  }
  return (
    <>
      <Head>
        <title>Job Card</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <Header />
        <SideBar />
        <main id="main" className="col-lg-10 main mt-0">
          <Row>
            <div className="col-lg-7">
              <div className="card">
                <div className="card-body">
                  <h1>Create Job Card</h1>
                  <hr
                    style={{
                      color: "#000000",
                      backgroundColor: "#000000",
                      height: 1.5,
                      padding: ".1rem",
                    }}
                  />
                    <form onSubmit={createJobCard}>

                      <div className="row mb-3">
                        <label
                          htmlFor="inputText"
                          className="col-sm-5 col-form-label"
                        >
                          Date :
                        </label>
                        <div className="col-sm-5">
                          <input
                            type="date"
                            name="date"
                            className="form-control"
                          />
                        </div>
                      </div>

                      <div className="row mb-3">
                        <label
                          htmlFor="inputText"
                          className="col-sm-5 col-form-label"
                        >
                          Vehicle No :
                        </label>
                        <div className="col-sm-5">
                          <input
                            type="text"
                            name="vehicle_no"
                            className="form-control"
                          />
                        </div>
                      </div>

                      <div className="row mb-3">
                        <label
                          htmlFor="inputText"
                          className="col-sm-5 col-form-label"
                        >
                          Mechanic Name :
                        </label>
                        <div className="col-sm-5">
                          <input
                            type="text"
                            name="mechanic_name"
                            className="form-control"
                          />
                        </div>
                      </div>

                      <div className="row mb-3">
                        <label
                          htmlFor="inputText"
                          className="col-sm-5 col-form-label"
                        >
                          Particular Work :
                        </label>
                        <div className="col-sm-5">
                          <input
                            type="text"
                            name="particular_work"
                            className="form-control"
                          />
                        </div>
                      </div>

                      <div className="row mb-3">
                        <label
                          htmlFor="inputText"
                          className="col-sm-5 col-form-label"
                        >
                          Parts Used :
                        </label>
                        <div className="col-sm-5">
                          <input
                            type="text"
                            name="parts_used"
                            className="form-control"
                          />
                        </div>
                      </div>

                      <div className="row mb-3">
                        <label
                          htmlFor="inputText"
                          className="col-sm-5 col-form-label"
                        >
                          Work Order Number :
                        </label>
                        <div className="col-sm-5">
                          <input
                            type="number"
                            name="work_order_no"
                            className="form-control"
                          />
                        </div>
                      </div>

                      <div className="row mb-3">
                        <label
                          htmlFor="inputText"
                          className="col-sm-5 col-form-label"
                        >
                          CRP Number :
                        </label>
                        <div className="col-sm-5">
                          <input type="number" name="crp_no" className="form-control" />
                        </div>
                      </div>

                      <div className="row mb-3">
                        <label
                          htmlFor="inputText"
                          className="col-sm-5 col-form-label"
                        >
                          Issue Voucher Number :
                        </label>
                        <div className="col-sm-5">
                          <input
                            type="text"
                            name="issue_voucher_number"
                            className="form-control"
                          />
                        </div>
                      </div>

                      <div className="row mb-3">
                        <label
                          htmlFor="inputText"
                          className="col-sm-5 col-form-label"
                        >
                          Remarks :
                        </label>
                        <div className="col-sm-5">
                          <input
                            type="text"
                            name="remarks"
                            className="form-control"
                          />
                        </div>
                      </div>

                      <div className="row mb-3">
                        <label
                          htmlFor="inputText"
                          className="col-sm-5 col-form-label"
                        >
                          Signature Of Incharge :
                        </label>
                        <div className="col-sm-5">
                          <input
                            type="text"
                            name="sign_of_mt_incharge"
                            className="form-control"
                          />
                        </div>
                      </div>

                      <div className="row mb-3">
                        <div className="col-sm-7">
                          <button
                            type="submit"
                            className="btn btn-primary"
                            style={{ float: "right" }}
                          >
                            Create Job Card
                          </button>
                        </div>
                      </div>
                    </form>
                </div>
              </div>
              <button
                className="btn btn-primary"
                style={{ float: "left" }}
                onClick={() => Router.back()}>
                Go Back
              </button>
            </div>
            <div className="col-lg-5">
              <div className="card">
                <div className="card-body">
                  <h1>Job Card List</h1>
                  <hr
                    style={{
                      color: "#000000",
                      backgroundColor: "#000000",
                      height: 1.5,
                      padding: ".1rem",
                    }}
                  />
                    <table className="table table-hover">
                      <thead>
                        <tr>
                          <th scope="col">Sl No.</th>
                          <th scope="col">Date</th>
                          <th scope="col">Vehicle No</th>
                          <th scope="col">Job</th>
                          <th scope="col">Mechanic Name</th>
                        </tr>
                      </thead>
                      <tbody style={
                        { cursor: "pointer" }
                      }>
                        {
                          cards.map((card, index) => {
                            return (
                              <tr key={
                                index + 1
                              }
                                onClick={
                                  () => OpenLink(card._id)
                                }>
                                <th scope="row">
                                  {index + 1}
                                </th>
                                <td>{card.date &&
                                  dateFormat(
                                    card.date,
                                    "dS mmmm, yyyy - dddd"
                                  )}</td>
                                <td>{
                                  card.vehicle_no
                                }</td>
                                <td>{
                                  card.particular_work
                                }</td>
                                <td>{card.mechanic_name}</td>
                              </tr>
                            )
                          })
                        }
                      </tbody>
                    </table>
                </div>
              </div>
            </div>
          </Row>
        </main>
      </main >
      <Scripts />
      <Script src="/assets/js/main.js"></Script>
    </>
  );
}
