import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Script from "next/script";
import Header from "../../components/Header";
import SideBar from "../../components/Sidebar";
import Scripts from "../../components/Scripts";
import { useEffect, useState } from "react";
import axios from "axios";
import Router from "next/router";
import dateFormat from "dateformat";


import { Button, Row } from 'react-bootstrap';
import Link from "next/link";

async function GetReceiveVouchers() {
    const res = await axios({
        url: "http://localhost:3000/receivevoucher/",
        method: "GET",
        withCredentials: true,
    });
    return res.data;
}

async function createReceiveVoucher(event) {
    event.preventDefault();
    var data = {
        vehicle_reg_no: event.target.vehicle_reg_no.value,
        vehicle_model: event.target.vehicle_model.value,
        vehicle_make: event.target.vehicle_make.value,
        vehicle_type: event.target.vehicle_type.value,
        date: event.target.date.value,
        kilometers_run: event.target.kilometers_run.value,
        quantity: event.target.quantity.value,
        rate: event.target.rate.value,
        receive_voucher_no: event.target.receive_voucher_no.value,
        station: event.target.station.value,
        items: event.target.items.value
    };

    const res = await axios({
        url: "http://localhost:3000/receivevoucher/add",
        withCredentials: true,
        method: "POST",

    data: data,
  });
}

export default function Home() {

    const [selectedValues, setSelectedValues] = useState([]);

    const handleChange = (selectedOptions) => {
        const values = selectedOptions.map((option) => option.value);
        setSelectedValues(values);
    };
    const [receiveVouchers, setReceiveVouchers] = useState([]);
    useEffect(() => {
        GetReceiveVouchers().then((data) => {
            setReceiveVouchers(data);
        });
    }, []);
    function OpenLink(link) {
        Router.push('/admin/workshop/' + link);
    }
    return (
        <>
            <Head>
                <title>Receive Voucher</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main className={styles.main}>
                <Header />
                <SideBar />
                <main id="main" className="col-lg-10 main mt-0">
                    <Row>
                        <div className="col-lg-7">
                            <div className="card">
                                <div className="card-body">
                                    <h1>Create Receive Voucher</h1>
                                    <hr
                                        style={{
                                            color: "#000000",
                                            backgroundColor: "#000000",
                                            height: 1.5,
                                            padding: ".1rem",
                                        }}
                                    />
                                        <form onSubmit={createReceiveVoucher}>
                                            <div className="row mb-3">
                                                <label
                                                    htmlFor="inputText"
                                                    className="col-sm-5 col-form-label"
                                                >
                                                    Date :
                                                </label>
                                                <div className="col-sm-5">
                                                    <input
                                                        type="date"
                                                        name="date"
                                                        className="form-control"
                                                    />
                                                </div>
                                            </div>

                    <div className="row mb-3">
                      <label
                        htmlFor="inputText"
                        className="col-sm-5 col-form-label"
                      >
                        Receive Voucher No :
                      </label>
                      <div className="col-sm-5">
                        <input
                          type="text"
                          name="receive_voucher_no"
                          className="form-control"
                        />
                      </div>
                    </div>

                    <div className="row mb-3">
                      <label
                        htmlFor="inputText"
                        className="col-sm-5 col-form-label"
                      >
                        Vehicle No :
                      </label>
                      <div className="col-sm-5">
                        <input
                          type="text"
                          name="vehicle_reg_no"
                          className="form-control"
                        />
                      </div>
                    </div>

                    <div className="row mb-3">
                      <label
                        htmlFor="inputText"
                        className="col-sm-5 col-form-label"
                      >
                        Vehicle Model :
                      </label>
                      <div className="col-sm-5">
                        <input
                          type="text"
                          name="vehicle_model"
                          className="form-control"
                        />
                      </div>
                    </div>

                    <div className="row mb-3">
                      <label
                        htmlFor="inputText"
                        className="col-sm-5 col-form-label"
                      >
                        Vehicle Make :
                      </label>
                      <div className="col-sm-5">
                        <input
                          type="text"
                          name="vehicle_make"
                          className="form-control"
                        />
                      </div>
                    </div>

                    <div className="row mb-3">
                      <label
                        htmlFor="inputText"
                        className="col-sm-5 col-form-label"
                      >
                        Vehicle Type :
                      </label>
                      <div className="col-sm-5">
                        <input
                          type="text"
                          name="vehicle_type"
                          className="form-control"
                        />
                      </div>
                    </div>

                    <div className="row mb-3">
                      <label
                        htmlFor="inputText"
                        className="col-sm-5 col-form-label"
                      >
                        kilometers Run :
                      </label>
                      <div className="col-sm-5">
                        <input
                          type="number"
                          name="kilometers_run"
                          className="form-control"
                        />
                      </div>
                    </div>



                                            <div className="row mb-3">
                                                <label
                                                    htmlFor="inputText"
                                                    className="col-sm-5 col-form-label"
                                                >
                                                    Items :
                                                </label>
                                                <div className="col-sm-5">
                                                <input
                                                        type="text"
                                                        name="items"
                                                        className="form-control"
                                                    />
                                                </div>
                                            </div>

                    <div className="row mb-3">
                      <label
                        htmlFor="inputText"
                        className="col-sm-5 col-form-label"
                      >
                        Quantity :
                      </label>
                      <div className="col-sm-5">
                        <input
                          type="number"
                          name="quantity"
                          className="form-control"
                        />
                      </div>
                    </div>

                    <div className="row mb-3">
                      <label
                        htmlFor="inputText"
                        className="col-sm-5 col-form-label"
                      >
                        Rate Per Unit :
                      </label>
                      <div className="col-sm-5">
                        <input
                          type="number"
                          name="rate"
                          className="form-control"
                        />
                      </div>
                    </div>

                    <div className="row mb-3">
                      <label
                        htmlFor="inputText"
                        className="col-sm-5 col-form-label"
                      >
                        Station :
                      </label>
                      <div className="col-sm-5">
                        <input
                          type="text"
                          name="station"
                          className="form-control"
                        />
                      </div>
                    </div>

                                            <div className="row mb-3">
                                                <div className="col-sm-7">
                                                    <button
                                                        type="submit"
                                                        className="btn btn-primary"
                                                        style={{ float: "right" }}
                                                    >
                                                        Create Receive Voucher
                                                    </button>
                                                </div>
                                            </div>
                                        </form>
                                </div>
                            </div>
                            <button
                                className="btn btn-primary"
                                style={{ float: "left" }}
                                onClick={() => Router.back()}>
                                Go Back
                            </button>
                        </div>
                        <div className="col-lg-5">
                            <div className="card">
                                <div className="card-body">
                                    <h1>Receive Voucher List</h1>
                                    <hr
                                        style={{
                                            color: "#000000",
                                            backgroundColor: "#000000",
                                            height: 1.5,
                                            padding: ".1rem",
                                        }}
                                    />
                                        <table className="table table-hover">
                                            <thead>
                                                <tr>
                                                    <th scope="col">Sl No.</th>
                                                    <th scope="col">Date</th>
                                                    <th scope="col">Receive Voucher No.</th>
                                                    <th scope="col">Vehicle No.</th>
                                                </tr>
                                            </thead>
                                            <tbody style={
                                                { cursor: "pointer" }
                                            }>
                                                {
                                                    receiveVouchers.map((receiveVoucher, index) => {
                                                        return (
                                                            <tr key={
                                                                index + 1
                                                            }
                                                                onClick={
                                                                    () => OpenLink(receiveVoucher._id)
                                                                }>
                                                                <th scope="row">
                                                                    {index + 1}
                                                                </th>
                                                                <td>{receiveVoucher.date &&
                                                                    dateFormat(
                                                                        receiveVoucher.date,
                                                                        "dS mmmm, yyyy - dddd"
                                                                    )}</td>
                                                                <td>{
                                                                    receiveVoucher.receive_voucher_no
                                                                }</td>
                                                                <td>{
                                                                    receiveVoucher.vehicle_reg_no
                                                                }</td>
                                                            </tr>
                                                        )
                                                    })
                                                }
                                            </tbody>
                                        </table>
                                </div>
                            </div>
                        </div>
                    </Row>
                </main>
            </main>
            <Scripts />
            <Script src="/assets/js/main.js"></Script>
        </>
    );
}
