import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { Button } from "react-bootstrap";


export default function LoginError() {
  // useEffect(() => {
  //   checkLogin();
  // });
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          height: "100vh",
          width: "100vw",
        }}
        className="opac-80"
      >
        <div className={styles.navbar}>
          <span
            className={styles.navbar_title}
            style={{
              textShadow: "2px 2px 4px rgba(0, 0, 0, 0.5)",
            }}
          >
            Fleet
            <span style={{ color: "red" }}>Management</span>
            System
          </span>
          <span className={styles.navbar_title_phone}>
            F<span style={{ color: "red" }}>M</span>S
          </span>
        </div>

        <div className={`${styles.middle} login_main`}>
          <div
            className={styles.form}
            style={{ opacity: 1, backgroundColor: "white", opacity: 0.8 }}
          >
            <Link href="/login">
              <Button variant="dark">Please Login To Access The Page</Button>
            </Link>
          </div>
        </div>

        <div
          className={`${styles.footer} opac-80`}
          style={{
            textShadow: "2px 2px 4px rgba(0, 0, 0, 0.5)",
          }}
        >
          Copyright 2023
        </div>
      </main>
    </>
  );
}
