import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Script from 'next/script'
import Header from '../../components/Header'
import SideBar from '../../components/Sidebar'
import Scripts from '../../components/Scripts'
import {useEffect, useState} from 'react'
import axios from 'axios'
import Router from 'next/router'

async function Getoilbalancce() {
    const res = await axios({url: "https://projectx-production.up.railway.app/oilstockregister/", method: "GET", withCredentials: true});
    console.log(res.data);
    return res.data;
}


export default function Home() {
    const [oilbalance, setoilbalance] = useState([]);
    useEffect(() => {
        Getoilbalancce().then((data) => {
            setoilbalance(data);
        });
    }, []);
    function OpenLink(link) {
        console.log(link);
        Router.push('/admin/fuel/recieve/' + link);
    }
    function OpenLink1(link) {
        console.log(link);
        Router.push('/admin/fuel/issue/' + link);
    }
    return (
        <>
            <Head>
                <title>List Drivers</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>

            </Head>
            <main className={
                styles.main
            }>
                <Header/>
                <SideBar/>

                <main id="main" className=" col-lg-9 main">
                    <h1>
                        OIL BALANCE
                    </h1>
                                <hr  style={{
                                    color: '#000000',
                                    backgroundColor: '#000000',
                                    height: 2.5,
                                    borderColor : '#000000'
                                    }}/>
                    <table className="table table-hover">
                        <thead>
                            <tr>
                                <th scope="col">Sl No</th>
                                <th scope="col">Balance</th>
                                <th scope="col">Date</th>
                                <th scope="col">Issued</th>
                                <th scope="col">Recived</th>
                               
                            </tr>
                        </thead>
                        <tbody style={
                            {cursor: "pointer"}
                        }>
                            {
                            oilbalance.map((oilbalances, index) => {
                                {var index1=index+1}
                                return (
                                    <tr key={
                                            index + 1
                                        }
                                      
                                        onClick={
                                          
                                            () =>   oilbalances.recivedd==true?OpenLink(oilbalances._id):OpenLink1(oilbalances._id)
                                    }>
                                        <td>{
                                         index1
                                        }
                                        {/* {console.log(oilbalances.Date)} */}
                                        </td>
                                        <td>{
                                             oilbalances.balance
                                            
                                        }</td>
                                      
                                        <td>{
                                            
                                             oilbalances.Date


                                        }</td>
                                        <td>{
                                            oilbalances.issueed==false?"":"YES"
                                           
                                        }</td>
                                        <td>{ oilbalances.issueed==true?"":"YES"
                                        }</td>
                                       
                                    </tr>
                                )
                            })
                        } </tbody>
                    </table>
                </main>

            </main>
            <Scripts/>
            <Script src="/assets/js/main.js"></Script>
        </>
    )
}
