import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Script from "next/script";
import Header from "../../components/Header";
import SideBar from "../../components/Sidebar";
import Scripts from "../../components/Scripts";
import { useEffect, useState } from "react";
import axios from "axios";
import Router from "next/router";
import dateFormat from "dateformat";

async function GetInspectionHistory() {
  const res = await axios({
    url: "http://localhost:3000/inspection/",
    method: "GET",
    withCredentials: true,
  });
  return res.data;
}

export default function Home() {
  const [inspection, setInspectionHistory] = useState([]);
  useEffect(() => {
    GetInspectionHistory().then((data) => {
      setInspectionHistory(data);
    });
  }, []);
  function OpenLink(link) {
    Router.push("/admin/inspection/" + link);
  }
  return (
    <>
      <Head>
        <title>Inspection History</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <Header />
        <SideBar />

        <main id="main" className=" col-lg-9 main">
          <h1>Inspection History</h1>
          <hr
            style={{
              color: "#000000",
              backgroundColor: "#000000",
              height: 2.5,
              borderColor: "#000000",
            }}
          />
          <table className="table table-hover">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Vehicle No</th>
                <th scope="col">Date</th>
                <th scope="col">Remarks</th>
              </tr>
            </thead>
            <tbody style={{ cursor: "pointer" }}>
              {inspection.map((data, index) => {
                return (
                  <tr key={index + 1} onClick={() => OpenLink(data._id)}>
                    <td>{index+1}</td>
                    <td>{data.vehicle && data.vehicle.registration_no}</td>
                    <td>
                      {dateFormat(
                        data.date,
                        "dS mmmm, yyyy - dddd"
                      )}
                    </td>
                    <td>{data.inspection_remarks}</td>
                  </tr>
                );
              })}{" "}
            </tbody>
          </table>
        </main>
      </main>
      <Scripts />
      <Script src="/assets/js/main.js"></Script>
    </>
  );
}
