import Head from 'next/head'
import Image from 'next/image'
import {Inter} from "next/font/google"
import styles from '@/styles/Home.module.css'
import Script from 'next/script'
import Link from 'next/link'
import Header from '../components/Header'
import SideBar from '../components/Sidebar'
import Footer from '../components/Footer'
import Scripts from '../components/Scripts'

const inter = Inter({subsets: ['latin']})

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>

            </Head>
            <main className={
                styles.main
            }>

                <Header/>
                <SideBar/>

                <main id="main" className="main"></main>

                <Footer/>

                <a href="#" className="back-to-top d-flex align-items-center justify-content-center">
                    <i className="bi bi-arrow-up-short"></i>
                </a>
            </main>
            <Scripts/>
            <Script src="/assets/js/main.js"></Script>
        </>
    )
}
