import { useRouter } from "next/router";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "@/pages/components/Header";
import SideBar from "@/pages/components/Sidebar";
import axios from "axios";
import { useEffect, useState, useRef } from "react";
import dateFormat from "dateformat";
import { Row, Col, Button, Modal } from "react-bootstrap";
import Link from "next/link";
import Scripts from "@/pages/components/Scripts";
import { useReactToPrint } from "react-to-print";

async function getOilBalance(id) {
  const res = await axios({
    url: "http://localhost:3000/oilstockregister/" + id,
    method: "GET",
    withCredentials: true,
  });
  return res.data;
}
const Post = () => {
  const router = useRouter();
  const [voucher, setVoucher] = useState({});
  const printRef = useRef();

  const handlePrint = useReactToPrint({
    content: () => printRef.current,
  });

  useEffect(() => {
    const { id } = router.query;
    getOilBalance(id).then((data) => {
      setVoucher(data);
      console.log(data);
    });
  }, [router.isReady]);

  return (
    <>
      <Head>
        <title>User Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <SideBar />
      <main className={styles.main}>
        <main id="main" className="col-11 mt-0 row opac-80">
          <Row>
            <div className="col-8 m-1 card">
              <div className="col-12 p-5" ref={printRef}>
                {voucher.recieved && (
                  <>
                    <h1 className="josefin-sans">Recieve Voucher</h1>
                    प्राप्तकर्ता अधिकारी द्वारा भरा जाने के लिए To be completed
                    by the Receiving Officer Issue/Expense (a) Vougher No
                    <hr />
                  </>
                )}

                {voucher.issued && (
                  <div>
                    <h1 className="josefin-sans">Issue Voucher</h1>
                    <hr />
                    To be completed by the Issuing Officer <br />
                    <br />
                    <p>
                      Issue Voucher No : <b> {voucher.issue_voucher_no}</b>
                    </p>
                    <p>
                      Unit/Estt : <b>M.T.O. CTC (T&IT)</b>
                    </p>
                    <p>
                      Station : <b>CRPF Dhurva Ranchi</b>
                    </p>
                    <p>
                      Date :{" "}
                      <b>
                        {voucher.date &&
                          dateFormat(voucher.date, "dS mmmm, yyyy - dddd")}
                      </b>
                    </p>
                    <p>
                      The articles enumerated below have been issued from{" "}
                      <b>Fuel Stock M.T.O. CTC (T&IT) </b>
                      in Part/Full compliance with
                    </p>
                    <p>
                      The articles enumerated below have been expended/issued
                      and demanded under the authority of
                    </p>
                    <table className="table">
                      <thead>
                        <tr>
                          <th scope="col">Sl No</th>
                          <th scope="col">Name</th>
                          <th scope="col">Quantity</th>
                          <th scope="col">Rate</th>
                          <th scope="col">Total Amount</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <th scope="row">1</th>
                          <td>{voucher.type.type}</td>
                          <td>{voucher.issued_amount}</td>
                          <td>{voucher.cost / voucher.issued_amount}</td>
                          <td>{voucher.cost}</td>
                        </tr>
                      </tbody>
                    </table>
                    <p>
                      Remarks : <b>{voucher.remarks}</b>
                    </p>
                    <div
                      style={{
                        display: "flex",
                        justifyContent: "space-around",
                        textAlign: "center",
                      }}
                    >
                      <div>
                        Signature of POL
                        <br /> Havaldar
                      </div>
                      <div>
                        Signature of Incharge
                        <br />
                        MT Section
                      </div>
                    </div>
                    {/* युनिट / स्थापना The N.1.0. Unit/Estt. स्थान Station. The
                  N.7.0. etc. ((si7) CRPF. Ohuswa Randhi नीचे लिखी वस्तुएं (क)
                  को दी गई/द्वारा प्राप्त हुई/द्वारा तैयार की गई। (ख) (ग) का
                  आंशिक या पूर्ण अनुपालन। The articles enumerated below have
                  been (a) issued to/received by/manufactured by.. in (b)
                  Part/Full compliance with (c). Otel 7/9/21 नीचे लिखी वस्तुएं
                  इस्तेमाल कर ली गई हैं/ दी गई है और .. क्रम Received issued in
                  Entered सन् 21 वस्तुएं 01, 100,30 ए० / यू० Sid Reg Arlelés
                  जापा No 1 2 A/U 3 कुल मात्रा Total Qty HED एस० S. 5 संख्या या
                  मात्रा Number or Quantity" के प्राधिकार के अधीन मांगी गई हैं।
                  डी०/ ई० पी० डब्ल्यू० D/E PW. अभ्युक्तियां Remarks यू० / एस०
                  U/S NO 7 B cost : 0 current_balance : 29 date :
                  "2023-05-28T00:00:00.000Z" issue_voucher_no :
                  "IV/POL/2/2023/MT-CTC(T&IT)" issued : true issued_amount : 1
                  previous_balance : 30 slno : 2 type :
                  "647324dff810da64858d63fa" __v : 0 _id :
                  "64738ee0efce5467cd0df165" */}
                  </div>
                )}
              </div>
            </div>
            <div className="col-3 m-1 card p-3">
              <Button onClick={handlePrint} className="w-100 mb-1 btn-success">
                Print Voucher
              </Button>
              <Link href={"/admin/fuel/add"}>
                <Button className="w-100 mb-1 btn-warning">
                  Update Balance
                </Button>
              </Link>
              <Link href={"/admin/fuel/allot"}>
                <Button className="w-100 mb-1 btn-dark">Allot Fuel</Button>
              </Link>

              <Link href={"/admin/fuel/addtype"}>
                <Button className="w-100 mb-1 btn-primary">Add Oil Type</Button>
              </Link>
            </div>
          </Row>
        </main>
      </main>
      <Scripts />
    </>
  );
};
export default Post;
