import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Script from "next/script";
import Header from "../../components/Header";
import SideBar from "../../components/Sidebar";
import Scripts from "../../components/Scripts";
import { useEffect, useState } from "react";
import axios from "axios";
import Link from "next/link";
import Router from "next/router";
import { Button } from "react-bootstrap";

async function GetItems() {
  const res = await axios({
    url: "http://localhost:3000/inventory/items",
    method: "GET",
    withCredentials: true,
  });
  return res.data;
}

export default function Home() {
  const [items, setItems] = useState([]);

  useEffect(() => {
    GetItems().then((data) => {
      setItems(data);
    });
  }, []);

  function OpenLink(link) {
    Router.push("/admin/inventory/item/" + link+"/history");
  }

  return (
    <>
      <Head>
        <title>Storage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <Header />
        <SideBar />

        <main id="main" className="col-10 main mt-0 opac-90">
          <h1>All Items</h1>
          <div className="col-lg-12 d-flex">
            <div className="col-lg-8 card m-1 p-4">
              <table className="table table-hover">
                <thead>
                  <tr>
                    <th scope="col">SL No</th>
                    <th scope="col">Item Name</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Cost of Each Item</th>
                    <th scope="col">Total Cost</th>
                    <th scope="col">Status</th>
                  </tr>
                </thead>
                <tbody style={{ cursor: "pointer" }}>
                  {items.map((item, index) => {
                    return (
                      <tr key={index + 1} onClick={() => OpenLink(item._id)}>
                        <>
                          <th scope="row">{index + 1} </th>
                          <td>{item.name}</td>
                          <td>{item.quantity}</td>
                          <td>{item.rate}</td>
                          <td>{item.amount}</td>
                          <td>{"Availaible"}</td>
                        </>
                      </tr>
                    );
                  })}{" "}
                </tbody>
              </table>
            </div>
            <div className="col-lg-3 card p-5 m-1">
              <Button
                onClick={() => {
                  Router.back();
                }}
                className="w-100 mb-1 btn-dark"
              >
                BACK
              </Button>

              <Link href={"/admin/inventory/add"}>
                <Button className="w-100 mb-1 btn-success">
                  Create New Item
                </Button>
              </Link>
              <Link href={"/admin/inventory/orders/order"}>
                <Button className="w-100 mb-1">Order Item</Button>
              </Link>
              <Link href={"/admin/inventory/issues/issue"}>
                <Button className="w-100 mb-1 btn-warning">
                  Issue an Item
                </Button>
              </Link>
              <Link href={"/admin/inventory/history"}>
                <Button className="w-100 mb-1 btn-light">History</Button>
              </Link>
            </div>
          </div>
        </main>
      </main>
      <Scripts />
      <Script src="/assets/js/main.js"></Script>
    </>
  );
}
