import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Script from "next/script";
import Header from "../../components/Header";
import SideBar from "../../components/Sidebar";
import Scripts from "../../components/Scripts";
import { useEffect, useState } from "react";
import axios from "axios";
import Link from "next/link";
import Router from "next/router";
import { Button, Row } from "react-bootstrap";

async function GetItems() {
  const res = await axios({
    url: "https://projectx-production.up.railway.app/inventory/items",
    method: "GET",
    withCredentials: true,
  });
  console.log(res);
  return res.data;
}

export default function Home() {
  const [items, setItems] = useState([]);

  useEffect(() => {
    GetItems().then((data) => {
      setItems(data);
    });
  }, []);

  function  OpenLink(link) {
      console.log(link);
      Router.push('/admin/inventory/items/'+link);
  }

  return (
    <>
      <Head>
        <title>Storage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <Header />
        <SideBar />

        <main id="main" className=" col-lg-9 main">
          <Row className="p-1">
            <h1>All Items</h1>
          </Row>
          <div className="col-lg-12 d-flex">
            <div className="col-lg-8 card m-1 p-4">
              <table className="table table-hover">
                <thead>
                  <tr>
                    <th scope="col">SL No</th>
                    <th scope="col">Item Name</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Cost of Each Item</th>
                    <th scope="col">Total Cost</th>
                    <th scope="col">Status</th>
                    
                  </tr>
                </thead>
                <tbody style={{ cursor: "pointer" }}>
                  {
                  items.map((item, index) => {
                    return (
                      <tr key={index + 1}
                       onClick={() => OpenLink(item._id)
                       }>
                        <>
                          <th scope="row">{index + 1} </th>
                          <td>{item.name}</td>
                          <td>{item.quantity}</td>
                          <td>{item.rate}</td>
                          <td>{item.amount}</td>
                          <td>{"Availaible"}</td>
                        </>
                      </tr>
                    );
                  })}{" "}
                </tbody>
              </table>
            </div>
            <div className="col-lg-3 card p-5 m-1">
              <Link href={"/admin/vehicles/add"}>
                <Button className="w-100 mb-1">Add New Item</Button>
              </Link>
              <Link href={"/admin/vehicles/add"}>
                <Button className="w-100 mb-1">Order Item</Button>
              </Link>
              <Link href={"/admin/vehicles/add"}>
                <Button className="w-100 mb-1">Issue an Item</Button>
              </Link>
              <Link href={"/admin/vehicles/add"}>
                <Button className="w-100 mb-1">History</Button>
              </Link>
              <Link href={"/admin"}>
                <Button className="w-100 mb-1">Back</Button>
              </Link>

            </div>
            
          </div>
        </main>
      </main>
      <Scripts />
      <Script src="/assets/js/main.js"></Script>
    </>
  );
}
