import { useRouter } from "next/router";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "../../../components/Header";
import SideBar from "../../../components/Sidebar";
import Link from "next/link";
import { Button, Row } from "react-bootstrap";
import axios from "axios";
import { useEffect, useState, useRef } from "react";
import ReactToPrint from "react-to-print";
import { AiFillPrinter } from "react-icons/ai";
import { IconContext } from "react-icons";

//const componentRef=useRef()
async function GetVehicles(id) {
  const res = await axios({
    url: "http://localhost:3000/vehicles/" + id,
    method: "GET",
    withCredentials: true,
  });

  return res.data;
}
async function GetOilDetails(id) {
  const res = await axios({
    url: "http://localhost:3000/oilstockregister/" + id,
    withCredentials: true,
    method: "GET",
  });
  return res.data;
}

function printDiv(divName) {
  if (typeof document !== "undefined") {
    if (document.getElementById(divName) != null) {
      var printContents = document.getElementById(divName).innerHTML;
    }
    var originalContents = document.body.innerHTML;
    document.body.innerHTML = printContents;
    window.print();
    document.body.innerHTML = originalContents;
  }
}
const Post = () => {
  const [oil, setOil] = useState({});
  const [vehicle, setVehicles] = useState({});
  const router = useRouter();
  const { id } = router.query;
  useEffect(() => {
    if (!router.isReady) return;
    const { id } = router.query;
    GetOilDetails(id).then((data) => {
      setOil(data);
      console.log(data);
    });
  }, [router.isReady]);

  useEffect(() => {
    var v = oil.vehicle_id;
    GetVehicles(v).then((data) => {
      setVehicles(data);
      console.log(data);
    });
  },[]);

  const componentRef = useRef();
  return (
    <>
      <Head>
        <title>Oil Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <SideBar />
      <main className={styles.main}>
        <div style={{ marginTop: "1rem ", height: "80%" }}>
          <div
            style={{
              fontSize: "1rem",
              marginTop: "1rem",
              right: 10,
              position: "absolute",
            }}
          >
            <IconContext.Provider
              value={{ color: "blue", className: "global-class-name" }}
            >
              <ReactToPrint
                trigger={() => (
                  <button>
                    <AiFillPrinter />
                  </button>
                )}
                content={() => componentRef.current}
                // onAfterPrint={  <Link href={"/admin/duties"}></Link>}
              />
            </IconContext.Provider>
          </div>
          <Row>
            <div id="printableArea" ref={componentRef} className="p-5">
              <div
                style={{
                  fontSize: "4rem",
                  marginTop: "1rem",
                  marginBottom: "2rem",
                  marginLeft: 10,
                  marginRight: 10,
                }}
              >
                <span>Oil DETAILS (ISSUED)</span>
                <hr
                  style={{
                    color: "#000000",
                    backgroundColor: "#000000",
                    height: 2.5,
                  }}
                />
              </div>

              <table class="table">
                {
                  <tbody>
                    <tr>
                      <th scope="row">1.</th>
                      <td>Date:</td>

                      <td>{oil.Date}</td>
                    </tr>

                    <tr>
                      <th scope="row">2.</th>
                      <td>Issued:</td>
                      <td>{oil.issued}</td>
                    </tr>
                    <tr>
                      <th scope="row">3.</th>
                      <td>Balance</td>
                      <td>{oil.balance}</td>
                    </tr>

                    <tr>
                      <th scope="row">4.</th>
                      <td>Remarks:</td>
                      <td>{oil.remarks}</td>
                    </tr>
                    <tr>
                      <th scope="row">5.</th>
                      <td>Signature of mto:</td>
                      <td>{oil.signature_of_mto == true ? "YES" : "NO"}</td>
                    </tr>
                    <tr>
                      <th scope="row">6.</th>
                      <td>Signature of havaldar:</td>
                      <td>
                        {oil.signature_of_pol_havaldar == true ? "YES" : "NO"}
                      </td>
                    </tr>
                    <tr>
                      <th scope="row">7.</th>
                      <td>VEHICLE NUMBER:</td>
                      <td>{vehicle.registration_no}</td>
                    </tr>
                  </tbody>
                }
              </table>
            </div>
            <div class="col d-flex justify-content-center">
              <div
                className="col-lg-3 card p-4 m-1 "
                style={{ maxHeight: "10vh" }}
              >
                <Link href={"/admin/vehicles/" + oil.vehicle_id}>
                  <Button className="w-100 mb-1">Get Vehicle Detail</Button>
                </Link>
              </div>
            </div>
          </Row>
        </div>
      </main>
    </>
  );
};
export default Post;
