import Scripts from "../Scripts";
import styles from "@/styles/Home.module.css";
import Script from "next/script";
import Header from "./Header";
import SideBar from "./Sidebar";
import Head from "next/head";
import { useSelector, useDispatch } from "react-redux";
import { useEffect } from "react";
import Router from "next/router";
import { checkIfLoggedIn } from "@/functions/loginAPI";
import { setUser } from "@/functions/redux/reducers/authReducer";

const AdminLayout = ({ children, title }) => {
  const user = useSelector((state) => state.auth.user);
  const dispatch = useDispatch();
  useEffect(() => {
    checkIfLoggedIn().then((res) => {
      if (res.status === 200) {
        dispatch(setUser(res.user));
      } else {
        Router.push("/login");
      }
    });
  }, []);
  return (
    <>
      <main className={styles.main}>
        <Head>
          <title>{title}</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.png" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        </Head>
        <Header user={user} title={title} />
        <SideBar />
        {children}
      </main>
      <Scripts />
      <Script src="/assets/js/main.js"></Script>
    </>
  );
};

export default AdminLayout;
