import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Script from "next/script";
import Link from "next/link";
import { Button } from "react-bootstrap";

export default function Home() {
  return (
    <>
      <Head>
        <title>Fleet Management System</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${styles.main_page} c`}>
        <div className={styles.landing_page}>
          <Image
            className={styles.landing_page_image}
            src="/assets/img/3.jpg"
            alt="The langing Image background"
            layout="fill"
            objectFit="cover"
            objectPosition="center"
          />
          <div className={styles.landing_page_content}>
            <Image
              src="/assets/img/CRPF-1.png"
              alt="landing page center image"
              width={300}
              height={300}
            />
            <Link href={"/login/"}>
              <div className={styles.landing_page_button}>
                <button type="button" className="btn btn-primary btn-lg">
                  Enter FMS
                </button>
              </div>
            </Link>
          </div>
        </div>

        {/* <Footer/> */}

        <a
          href="#"
          className="back-to-top d-flex align-items-center justify-content-center"
        >
          <i className="bi bi-arrow-up-short"></i>
        </a>

        {/* <Scripts/> */}
        <Script src="/assets/js/main.js"></Script>
      </main>
    </>
  );
}
