import Head from 'next/head'
import Image from 'next/image'
import {Inter} from "next/font/google"
import styles from '@/styles/Home.module.css'
import Script from 'next/script'
import Link from 'next/link'
import {Button} from 'react-bootstrap'

const inter = Inter({subsets: ['latin']})

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>

            </Head>
            <main className={`${
                styles.main
            } c`}>
                {/*    
    <Header/>
    <SideBar/> */}

                <Link href={'/login/'}>
                    <Button variant="primary">Admin</Button>
                </Link>


                {/* <Footer/> */}

                <a href="#" className="back-to-top d-flex align-items-center justify-content-center">
                    <i className="bi bi-arrow-up-short"></i>
                </a>


                {/* <Scripts/> */}
                <Script src="/assets/js/main.js"></Script>
            </main>
        </>
    )
}
