import axios from 'axios';
import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Router from 'next/router';

export default function Login() {
  async function UserLogin(event) {
    console.log("HIII");
    event.preventDefault();
    let data = {
      username: event.target.username.value,
      password: event.target.password.value,
    };
    const res = await axios({
      method: "POST",
      url: "https://projectx-production.up.railway.app/login",
      data: data,
      withCredentials: true,
    });

    if (res.status === 200) {
      Router.push("/admin/");
    }else{
      alert("Wrong Username or Password");
    }
  }

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          height: "100vh",
          width: "100vw",
        }}
      >
        <div className={styles.navbar}>
          <span className={styles.navbar_title}>
            Fleet
            <span style={{ color: "red" }}>Management</span>
            System
          </span>
          <span className={styles.navbar_title_phone}>
            F<span style={{ color: "red" }}>M</span>S
          </span>
        </div>

        <div className={styles.middle}>
          <div className={styles.form}>
            <form onSubmit={UserLogin}>
              <div className={styles.form_inputs}>
                <div>
                  <span className={styles.input_label}>Username</span>
                  <br></br>
                  <input
                    type="text"
                    name="username"
                    placeholder="Enter Username"
                    className={styles.input_field}
                  ></input>
                </div>
                <div style={{ marginTop: "1rem" }}>
                  <span className={styles.input_label}>Password</span>
                  <br></br>
                  <input
                    type="password"
                    name="password"
                    placeholder="Enter Password"
                    className={styles.input_field}
                  ></input>
                  <span
                    style={{
                      float: "right",
                      color: "blue",
                    }}
                  >
                    <u>Forgot Password ?</u>
                  </span>
                </div>

                <div style={{ marginTop: "2rem" }}>
                  <input type="checkbox" />
                  Remember me
                </div>
              </div>
              <div style={{ marginTop: "2rem" }}>
                <button className={styles.login_button} type='submit'>LOGIN</button>
              </div>
            </form>
          </div>
        </div>

        <div className={styles.footer}>Copyright 2023</div>
      </main>
    </>
  );
}
