import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import { UserLogin } from "@/functions/loginAPI";
import { checkIfLoggedIn } from "@/functions/loginAPI";
import { useDispatch } from "react-redux";
import { setUser } from "@/functions/redux/reducers/authReducer";
import Router from "next/router";

export default function Login() {
  const [loginSpinner, setLoginSpinner] = useState(false);
  const [wrongPassword, setWrongPassword] = useState("");
  const [wrongCredentials, setWrongCredentials] = useState("");
  const dispatch = useDispatch();
  useEffect(() => {
    checkIfLoggedIn().then((res) => {
      if (res.status === 200) {
        dispatch(setUser(res.user));
        Router.push("/admin/duties");
      }
    });
  }, []);
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          height: "100vh",
          width: "100vw",
          backgroundColor: "white",
        }}
        className="opac-80"
      >
        <div className={styles.navbar}>
          <span
            className={styles.navbar_title}
            style={{
              textShadow: "2px 2px 4px rgba(0, 0, 0, 0.5)",
            }}
          >
            Fleet
            <span style={{ color: "red" }}>Management</span>
            System
          </span>
          <span className={styles.navbar_title_phone}>
            F<span style={{ color: "red" }}>M</span>S
          </span>
        </div>

        <div className={`${styles.middle} login_main`}>
          <div className={styles.form} style={{ opacity: 0.8 }}>
            <form
              onSubmit={async () => {
                let res = await UserLogin(event);
                if (res.status === 200) {
                  setLoginSpinner(true);
                  Router.push("/admin/duties");
                }
                if (res.status === 401) {
                  setWrongPassword(true);
                  setLoginSpinner(false);
                }
                if (res.status === 404) {
                  setWrongCredentials(true);
                  setLoginSpinner(false);
                }
              }}
              style={{ width: "80%", margin: "2rem" }}
            >
              <div className="text-center" style={{ width: "100%" }}>
                <h1
                  className="josefin-sans"
                  style={{
                    textShadow: "2px 2px 4px rgba(0, 0, 0, 0.5)",
                  }}
                >
                  CRPF Login
                </h1>
                <hr />
                <br />
              </div>
              <div>
                <span className={styles.input_label}>Email / Username</span>
                <br></br>
                <input
                  type="text"
                  name="username"
                  placeholder="Enter Username"
                  className={styles.input_field}
                  style={{ color: "black" }}
                  onFocus={() => {
                    setWrongPassword("");
                    setWrongCredentials("");
                  }}
                ></input>
              </div>

              <div style={{ marginTop: "1rem" }}>
                <span className={styles.input_label}>Password</span>
                <br></br>
                <input
                  type="password"
                  name="password"
                  placeholder="Enter Password"
                  className={styles.input_field}
                  style={{ color: "black" }}
                  onFocus={() => {
                    setWrongPassword("");
                    setWrongCredentials("");
                  }}
                ></input>
                <div style={{ textAlign: "center" }}>
                  <br></br>
                  {wrongPassword ? (
                    <span style={{ color: "red" }}>
                      <i>Wrong Password</i>
                    </span>
                  ) : (
                    ""
                  )}
                </div>
                <div className="text-center">
                  {wrongCredentials ? (
                    <span style={{ color: "red" }}>
                      <i>Wrong Credentials</i>
                    </span>
                  ) : (
                    ""
                  )}
                </div>
                <span
                  style={{
                    float: "right",
                    color: "blue",
                    marginTop: "1rem",
                  }}
                >
                  <u>Forgot Password ?</u>
                </span>
              </div>
              <div style={{ marginTop: "4rem" }}>
                {!loginSpinner ? (
                  <button className={styles.login_button} type="submit">
                    LOGIN
                  </button>
                ) : (
                  <button
                    className={styles.login_button}
                    type="button"
                    disabled
                  >
                    <span
                      className="spinner-border spinner-border-sm"
                      role="status"
                      aria-hidden="true"
                    ></span>
                    Loading...
                  </button>
                )}
              </div>
            </form>
          </div>
        </div>

        <div
          className={`${styles.footer} bg-white`}
          style={{
            textShadow: "2px 2px 4px rgba(0, 0, 0, 0.5)",
          }}
        >
          Copyright 2023
        </div>
      </main>
    </>
  );
}
