import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Script from "next/script";
import Header from "../../components/Header";
import SideBar from "../../components/Sidebar";
import Scripts from "../../components/Scripts";
import { useEffect, useState } from "react";
import axios from "axios";
import "react-toastify/dist/ReactToastify.css";
import dynamic from "next/dynamic";

const MapWithNoSSR = dynamic(async() =>import("./Map"), {
  ssr: false,
});

async function GetUser() {
  const res = await axios({
    url: "http://localhost:3000/users/get_user_details",
    method: "GET",
    withCredentials: true,
  });
  return res.data;
}

export default function Home() {
  const [user, setUser] = useState([]);
  useEffect(() => {
    GetUser().then((data) => {
      setUser(data);
    });
  }, []);

  return (
    <>
      <Head>
        <title>Tracking</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <Header />
        <SideBar />
        <main id="main" className="main col-10 mt-0">
          <MapWithNoSSR />
        </main>
      </main>
      <Scripts />
      <Script src="/assets/js/main.js"></Script>
    </>
  );
}
