import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Script from "next/script";
import Header from "../../components/Header";
import SideBar from "../../components/Sidebar";
import Scripts from "../../components/Scripts";
import { useEffect, useState } from "react";
import axios from "axios";
import Link from "next/link";
import Router from "next/router";
import { Button, Row } from "react-bootstrap";

async function GetVehicles() {
  const res = await axios({
    url: "http://localhost:3000/vehicles/",
    method: "GET",
    withCredentials: true,
  });
  return res.data;
}

export default function Home() {
  const [vehicles, setVehicles] = useState([]);
  const [updateOption, setupdateOption] = useState(false);
  const [deleteOption, setdeleteOption] = useState(false);

  useEffect(() => {
    GetVehicles().then((data) => {
      data.sort((a, b) => a.vehicle_sl_no - b.vehicle_sl_no);
      setVehicles(data);
    });
  }, []);

  function OpenLink(link) {
    Router.push("/admin/vehicles/vehicle/" + link);
  }
  return (
    <>
      <Head>
        <title>List Vehicles</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <Header />
        <SideBar />

        <main id="main" className="col-lg-11 main mt-0 opac-80">
          <div className="col-lg-12 d-flex">
            <div className="col-lg-8 m-1">
              <div>
                <h2>Available Vehicles</h2>
                <div className="card p-3">
                  <table className="table table-hover">
                    <thead>
                      <tr>
                        <th scope="col">CRP No</th>
                        <th scope="col">Vehicle Name</th>
                        <th scope="col">Type</th>
                        <th scope="col">Available</th>
                        {updateOption && <th scope="col">UPDATE</th>}
                        {deleteOption && <th scope="col">DELETE</th>}
                      </tr>
                    </thead>
                    <tbody style={{ cursor: "pointer" }}>
                      {vehicles.map((vehicle, index) => {
                        if (vehicle.available) {
                          return (
                            <tr
                              key={index + 1}
                              onClick={() => OpenLink(vehicle._id)}
                            >
                              <th scope="row" className="col-1">
                                {vehicle.vehicle_crp_no}{" "}
                              </th>
                              <td>{vehicle.name}</td>
                              <td>{vehicle.vehicle_type}</td>
                              <td>
                                {vehicle.available && (
                                  <span style={{ color: "green" }}>
                                    Available
                                  </span>
                                )}
                                {!vehicle.available && (
                                  <span style={{ color: "red" }}>On Duty</span>
                                )}
                              </td>
                            </tr>
                          );
                        }
                      })}
                    </tbody>
                  </table>
                </div>
              </div>
              <div>
                <h2>Vehicles On Duty</h2>
                <div className="card p-3">
                  <table className="table table-hover">
                    <thead>
                      <tr>
                        <th scope="col">CRP No</th>
                        <th scope="col">Vehicle Name</th>
                        <th scope="col">Type</th>
                        <th scope="col">Available</th>
                      </tr>
                    </thead>
                    <tbody style={{ cursor: "pointer" }}>
                      {vehicles.map((vehicle, index) => {
                        if (vehicle.available === false) {
                          return (
                            <tr
                              key={index + 1}
                              onClick={() => OpenLink(vehicle._id)}
                            >
                              <th scope="row" className="col-1">
                                {vehicle.vehicle_crp_no}{" "}
                              </th>
                              <td>{vehicle.name}</td>
                              <td>{vehicle.vehicle_type}</td>
                              <td>
                                {vehicle.available && (
                                  <span style={{ color: "green" }}>
                                    Available
                                  </span>
                                )}
                                {!vehicle.available && (
                                  <span style={{ color: "red" }}>On Duty</span>
                                )}
                              </td>
                            </tr>
                          );
                        }
                      })}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
            <div
              className="col-lg-3 card p-5 mt-5"
              style={{ maxHeight: "50vh" }}
            >
              <Button
                onClick={() => {
                  Router.back();
                }}
                className="w-100 mb-1 btn-dark"
              >
                BACK
              </Button>
              <Link href={"/admin/vehicles/add"}>
                <Button className="w-100 mb-1 btn-success">Add Vehicle</Button>
              </Link>
              <Link href={"/admin/vehicles/"}>
                <Button className="w-100 mb-1">All Vehicles</Button>
              </Link>
            </div>
          </div>
        </main>
      </main>
      <Scripts />
      <Script src="/assets/js/main.js"></Script>
    </>
  );
}
