import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Script from "next/script";
import Header from "../../components/Header";
import SideBar from "../../components/Sidebar";
import Scripts from "../../components/Scripts";
import { useEffect, useState } from "react";
import axios from "axios";
import Link from "next/link";
import Router from "next/router";
import { Button, Row } from "react-bootstrap";

async function GetVehicles() {
  const res = await axios({
    url: "https://projectx-production.up.railway.app/vehicles/",
    method: "GET",
    withCredentials: true,
  });
  return res.data;
}

export default function Home() {
  const [vehicles, setVehicles] = useState([]);
  const [updateOption, setupdateOption] = useState(false);
  const [deleteOption, setdeleteOption] = useState(false);
  const [deleteWarning, setDeleteWaring] = useState(false);

  useEffect(() => {
    GetVehicles().then((data) => {
      data.sort((a, b) => a.vehicle_sl_no - b.vehicle_sl_no);
      setVehicles(data);
    });
  }, []);

  function deleteVehicleWarning() {
    if (deleteWarning == true) {
      setupdateOption(false);
    } else {
      setupdateOption(true);
      setdeleteOption(false);
    }
  }

  function toggleUpdate() {
    if (updateOption == true) {
      setupdateOption(false);
    } else {
      setupdateOption(true);
      setdeleteOption(false);
    }
  }

  function toggleDelete() {
    if (deleteOption == true) {
      setdeleteOption(false);
    } else {
      setdeleteOption(true);
      setupdateOption(false);
    }
  }
  function OpenLink(link) {
    Router.push("/admin/vehicles/" + link);
  }
  return (
    <>
      <Head>
        <title>List Vehicles</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <Header />
        <SideBar />

        <main id="main" className="col-lg-11 main mt-0">
          <Row className="p-1">
            <h1>All Vehicles</h1>
          </Row>
          <div className="col-lg-12 d-flex">
            <div className="col-lg-8 card m-1 p-4">
              <table className="table table-hover">
                <thead>
                  <tr>
                    <th scope="col">CRP No</th>
                    <th scope="col">Vehicle Name</th>
                    <th scope="col">Type</th>
                    <th scope="col">Available</th>
                    {updateOption && <th scope="col">UPDATE</th>}
                    {deleteOption && <th scope="col">DELETE</th>}
                  </tr>
                </thead>
                <tbody style={{ cursor: "pointer" }}>
                  {vehicles.map((vehicle, index) => {
                    return (
                      <tr key={index + 1} onClick={() => OpenLink(vehicle._id)}>
                        {!deleteWarning && (
                          <>
                            <th scope="row">{vehicle.vehicle_crp_no} </th>
                            <td>{vehicle.name}</td>
                            <td>{vehicle.vehicle_type}</td>
                            <td>{"Available"}</td>
                            {updateOption && (
                              <td>
                                <Button className="btn-success">UPDATE</Button>
                              </td>
                            )}
                            {deleteOption && (
                              <td>
                                <Button
                                  className="btn-danger"
                                  onClick={deleteVehicleWarning}
                                >
                                  DELETE
                                </Button>
                              </td>
                            )}
                          </>
                        )}
                        {deleteWarning && (
                          <>Are you sure want to Delete {vehicle.name}</>
                        )}
                      </tr>
                    );
                  })}{" "}
                </tbody>
              </table>
            </div>
            <div className="col-lg-3 card p-5 m-1">
              <Link href={"/admin/vehicles/add"}>
                <Button className="w-100 mb-1">Add Vehicle</Button>
              </Link>
            </div>
          </div>
        </main>
      </main>
      <Scripts />
      <Script src="/assets/js/main.js"></Script>
    </>
  );
}
