import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Script from 'next/script'
import Header from '../../components/Header'
import SideBar from '../../components/Sidebar'
import Scripts from '../../components/Scripts'
import {useEffect, useState} from 'react'
import axios from 'axios'
import Router from 'next/router'

async function GetVehicles() {
    const res = await axios({url: "http://localhost:3000/vehicles/", method: "GET", withCredentials: true});
    return res.data;
}


export default function Home() {
    const [vehicles, setVehicles] = useState([]);
    useEffect(() => {
        GetVehicles().then((data) => {
            data.sort((a, b) => a.vehicle_sl_no - b.vehicle_sl_no);
            setVehicles(data);
        });
    }, []);
    function OpenLink(link) {
        console.log(link);
        Router.push('/admin/vehicles/' + link);
    }
    return (
        <>
            <Head>
                <title>List Vehicles</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>

            </Head>
            <main className={
                styles.main
            }>
                <Header/>
                <SideBar/>

                <main id="main" className=" col-lg-9 main">
                    <h1>
                        All Vehicles
                    </h1>
                    <hr></hr>
                    <table className="table table-hover">
                        <thead>
                            <tr>
                                <th scope="col">Sl No</th>
                                <th scope="col">Vehicle Name</th>
                                <th scope="col">Type</th>
                                <th scope="col">Available</th>
                            </tr>
                        </thead>
                        <tbody style={
                            {cursor: "pointer"}
                        }>
                            {
                            vehicles.map((vehicle, index) => {
                                return (
                                    <tr key={
                                            index + 1
                                        }
                                        onClick={
                                            () => OpenLink(vehicle._id)
                                    }>
                                        <th scope="row">
                                            {
                                            vehicle.vehicle_sl_no
                                        } </th>
                                        <td>{
                                            vehicle.vehicle_no
                                        }</td>
                                        <td>{
                                            vehicle.vehicle_type
                                        }</td>
                                        <td>{
                                            vehicle.category
                                        }</td>
                                        <td>{"Available"}</td>
                                    </tr>
                                )
                            })
                        } </tbody>
                    </table>
                </main>

            </main>
            <Scripts/>
            <Script src="/assets/js/main.js"></Script>
        </>
    )
}
